#
# yaml file to create ragsc conda environment on non-linux installations
#
name: ragsc 
channels:
  - conda-forge
dependencies:
  - python=3.12
  - scanpy
  - jupyterlab
  - langchain
  - loguru
  - mypy
  - markdown
  - numpy
  - pandas
  - polars
  - pytest
  - jupyter-lsp
  - jupyter-lsp-python
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-brew
  - r-callr
  - r-codetools
  - r-collections
  - r-commonmark
  - r-cpp11
  - r-crayon
  - r-cyclocomp
  - r-desc
  - r-digest
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-fastmap
  - r-fs
  - r-glue
  - r-highr
  - r-htmltools
  - r-jsonlite
  - r-knitr
  - r-languageserver
  - r-lazyeval
  - r-lifecycle
  - r-lintr
  - r-magrittr
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-prettyunits
  - r-processx
  - r-ps
  - r-purrr
  - r-r.cache
  - r-r.methodss3
  - r-r.oo
  - r-r.utils
  - r-r6
  - r-rematch2
  - r-remotes
  - r-repr
  - r-rex
  - r-rlang
  - r-roxygen2
  - r-rprojroot
  - r-soupx
  - r-stringi
  - r-stringr
  - r-styler
  - r-tibble
  - r-utf8
  - r-vctrs
  - r-withr
  - r-xfun
  - r-xml2
  - r-xmlparsedata
  - r-yaml
  - ruff
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - sqlalchemy
  - statsmodels
  - yaml
  - pip
  - pip:
    - langchain-community
    - langchain-openai
    - chromadb
    - sentence-transformers
